### ISSUE TITLE
Could not retrieve methods TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by roosnic1** [oauth-io/oauth-js#73]
Hi

I have a default ember.js web app that was created with ember-cli.
☮ ember -v
version: 1.13.8
node: 0.12.4
npm: 2.13.4
os: darwin x64

I installed OAuth.js with bower and include it in the app. I can call OAuth.initialize('xxx') with my public key without problems. When I call Auth.popup('twitter') a popup opens and I can login to my Twitter account and allow the application to access my data. But as soon as the popup closes the console shows the following error and neither the "done" nor the "error" callback gets called.

Could not retrieve methods TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.generateMethods (http://localhost:4200/assets/vendor.js:90870:30)
    at http://localhost:4200/assets/vendor.js:91264:17
    at _fulfilled (http://localhost:4200/assets/vendor.js:96560:54)
    at Promise.then.Q.nextTick.self.promiseDispatch.done (http://localhost:4200/assets/vendor.js:96589:30)
    at Promise.promise.promiseDispatch (http://localhost:4200/assets/vendor.js:96522:13)
    at http://localhost:4200/assets/vendor.js:96330:44
    at runSingle (http://localhost:4200/assets/vendor.js:95863:13)
    at MessagePort.flush (http://localhost:4200/assets/vendor.js:95851:13)

Any ideas what is wrong?

Thanks.

**Comment by roosnic1** [comment]
Sorry my bad. The error doesn't crash the popup function and the promises get's resolved. I once again learned this != this. Stupid me.
